# Generated by Django 6.0.5 on 2026-05-28 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('alt_phone', models.CharField(blank=True, max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('house_type', models.CharField(choices=[('bedsitter', 'Bedsitter'), ('1br', '1 Bedroom'), ('2br', '2 Bedroom'), ('3br', '3 Bedroom'), ('4br', '4+ Bedroom')], max_length=20)),
                ('monthly_rent', models.PositiveIntegerField()),
                ('location_neighbourhood', models.CharField(blank=True, max_length=100)),
                ('location_landmark', models.CharField(blank=True, max_length=200)),
                ('has_tiles', models.BooleanField(default=False)),
                ('has_water', models.BooleanField(default=False)),
                ('water_source', models.CharField(blank=True, choices=[('county', 'County supply'), ('borehole', 'Borehole'), ('tank', 'Raised tank'), ('truck', 'Water truck')], max_length=20)),
                ('water_schedule', models.CharField(blank=True, max_length=150)),
                ('has_hot_shower', models.BooleanField(default=False)),
                ('has_internet', models.BooleanField(default=False)),
                ('parking_capacity', models.PositiveSmallIntegerField(default=0)),
                ('electricity_billing', models.CharField(choices=[('separate', 'Separate bill (prepaid/postpaid)'), ('included', 'Included in rent'), ('solar', 'Solar only')], default='separate', max_length=20)),
                ('has_shop_room', models.BooleanField(default=False)),
                ('extra_features', models.TextField(blank=True, help_text='One per line, e.g. ✓ Large compound')),
                ('image1', models.ImageField(blank=True, upload_to='enyumba/')),
                ('image2', models.ImageField(blank=True, upload_to='enyumba/')),
                ('image3', models.ImageField(blank=True, upload_to='enyumba/')),
                ('image4', models.ImageField(blank=True, upload_to='enyumba/')),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('flag_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enyumba.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_ip', models.GenericIPAddressField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enyumba.property')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
