# Generated by Django 6.0.5 on 2026-06-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enyumba', '0001_initial'),
    ]

    operations = [
    ]
