# Generated by Django 6.0.5 on 2026-05-28 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enyumba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='ads/')),
                ('link_url', models.URLField(help_text='Where the ad clicks through (e.g., WhatsApp link, website)')),
                ('position', models.CharField(choices=[('sidebar', 'Sidebar (search page)'), ('footer', 'Footer (all pages)'), ('between_listings', 'Between property listings'), ('home_top', 'Homepage top banner'), ('property_sidebar', 'Inside property detail page')], default='sidebar', max_length=50)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers show first')),
                ('amount_paid', models.PositiveIntegerField(help_text='KES paid')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enyumba.advertiser')),
            ],
        ),
    ]
