# Generated by Django 6.0.5 on 2026-06-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enyumba', '0002_add_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_tier',
            field=models.CharField(choices=[('free', 'Free (bottom)'), ('standard', 'Standard - KES 100/month'), ('featured', 'Featured - KES 300/month'), ('premium', 'Premium - KES 500/month')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='M-Pesa transaction ID', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='promotion_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='tier_expiry',
            field=models.DateTimeField(blank=True, help_text='When the paid tier expires', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_paid',
            field=models.PositiveIntegerField(default=0, help_text='Total amount paid by landlord (KES)'),
        ),
    ]
