# Generated by Django 6.0.5 on 2026-05-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enyumba', '0002_advertiser_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('global', 'Global - All pages (top or bottom)'), ('sidebar', 'Sidebar (search page)'), ('footer', 'Footer (all pages)'), ('between_listings', 'Between property listings'), ('home_top', 'Homepage top banner'), ('property_sidebar', 'Inside property detail page')], default='sidebar', max_length=50),
        ),
    ]
