# Generated by Django 6.0.5 on 2026-05-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enyumba', '0003_alter_advertisement_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='baths',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='beds',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='blocked_dates',
            field=models.TextField(blank=True, help_text='Comma‑separated dates (YYYY-MM-DD) that are booked'),
        ),
        migrations.AddField(
            model_name='property',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum number of people', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='catering_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='cleaning_fee',
            field=models.PositiveIntegerField(default=0, help_text='One‑time cleaning fee (KES)'),
        ),
        migrations.AddField(
            model_name='property',
            name='conference_notes',
            field=models.TextField(blank=True, help_text='Parking, accessibility, etc.'),
        ),
        migrations.AddField(
            model_name='property',
            name='deposit',
            field=models.PositiveIntegerField(blank=True, help_text='Lease deposit (KES)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='full_day_rate',
            field=models.PositiveIntegerField(blank=True, help_text='KES for 8 hours', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='half_day_rate',
            field=models.PositiveIntegerField(blank=True, help_text='KES for 4 hours', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_projector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_sound_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_whiteboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='hourly_rate',
            field=models.PositiveIntegerField(blank=True, help_text='KES per hour', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='max_nights',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='min_lease_months',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='property',
            name='min_nights',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='nightly_rate',
            field=models.PositiveIntegerField(blank=True, help_text='KES per night', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('lease', 'Long‑term Lease (monthly)'), ('airbnb', 'Short‑term / Airbnb (nightly)'), ('conference', 'Conference Facility')], default='lease', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='total_units',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of houses/units in this property'),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_number',
            field=models.CharField(blank=True, help_text='e.g., House A, Unit 2 – if listing individually', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='house_type',
            field=models.CharField(blank=True, choices=[('bedsitter', 'Bedsitter'), ('1br', '1 Bedroom'), ('2br', '2 Bedroom'), ('3br', '3 Bedroom'), ('4br', '4+ Bedroom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='monthly_rent',
            field=models.PositiveIntegerField(blank=True, help_text='For lease listings only', null=True),
        ),
    ]
