# Generated by Django 6.0.5 on 2026-05-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enyumba', '0004_property_baths_property_bedrooms_property_beds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_terrazzo',
            field=models.BooleanField(default=False, help_text='Terrazzo floor finishing'),
        ),
        migrations.AddField(
            model_name='property',
            name='max_guests',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
