# Generated by Django 6.0.5 on 2026-05-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enyumba', '0005_property_has_terrazzo_property_max_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='capacity_range',
            field=models.CharField(blank=True, choices=[('0_20', 'Up to 20 people'), ('20_30', '20 - 30 people'), ('30_50', '30 - 50 people'), ('50_100', '50 - 100 people'), ('100_plus', '100+ people')], help_text='Select typical capacity range', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='compound_name',
            field=models.CharField(blank=True, help_text="Name of the compound (e.g., 'Sunrise Apartments')", max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='is_in_compound',
            field=models.BooleanField(default=False, help_text='Is this property part of a compound (multiple units on same plot)?'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_units_in_compound',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many total units exist in this compound?', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Exact maximum number of people (optional)', null=True),
        ),
    ]
