# Generated by Django 6.0.5 on 2026-06-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enyumba', '0006_property_capacity_range_property_compound_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_furnished',
            field=models.BooleanField(default=False, help_text='For rent listings only'),
        ),
        migrations.AlterField(
            model_name='property',
            name='deposit',
            field=models.PositiveIntegerField(blank=True, help_text='Deposit (usually 1 month rent)', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='min_lease_months',
            field=models.PositiveSmallIntegerField(default=6, help_text='Minimum lease period in months'),
        ),
        migrations.AlterField(
            model_name='property',
            name='monthly_rent',
            field=models.PositiveIntegerField(blank=True, help_text='For rent/lease listings only', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('rent', 'Monthly Rent (rolling contract)'), ('lease', 'Long‑term Lease (6+ months)'), ('airbnb', 'Short‑stay / Airbnb (nightly)'), ('conference', 'Conference Facility (hourly)')], default='rent', max_length=20),
        ),
    ]
